### ISSUE TITLE
Getting ac-model and ac-options attributes must be set error even though they are set

### ISSUE THREAD

**Issue by PocketDealHunter** [john-oc/acute-select#25]
Here is my ac-select tag

`<ac-select ac-model="selectedColour" ac-options="c.name for c in colours"  ac-change="colourChanged(value)"></ac-select>`

Using angular 1.2.1 with requireJS

Full error -

`ac-model and ac-options attributes must be set <div class="ac-select-wrapper ng-isolate-scope" ng-keydown="keyHandler($event)" tabindex="999" ac-focus="wrapperFocus" ng-focus="comboFocus = true" ac-model="selectedColour" ac-options="c.name for c in colours" ac-change="colourChanged(value)">`

**Comment by john-oc** [comment]
If you're getting the message "ac-options and ac-model attributes must be set", even though you've set the attributes, it's most likely because the scope variable pointed to by the ac-model attribute is undefined when ac-select initialises. E.g. if you have ac-model="myModel", try including the line

$scope.myModel = null;
or

$scope.myModel = [some value];
at the start of your controller.
